// Compact offline word list for the passphrase generator (Phase 33). Short,
// common, unambiguous English words. Entropy is computed from the *actual* list
// length (see pwgen.ts), so the security claim stays honest regardless of size.
// Embedded (no network) to keep the offline invariant intact.
export const WORDS: readonly string[] = [
  "able", "acid", "acorn", "actor", "adapt", "agent", "album", "alert", "alien", "alloy",
  "amber", "angle", "ankle", "apple", "apron", "arbor", "arch", "arena", "armor", "arrow",
  "aspen", "atlas", "atom", "aunt", "avoid", "awake", "axis", "bacon", "badge", "baker",
  "banjo", "barge", "basil", "basin", "batch", "beach", "beam", "bean", "bear", "beard",
  "beast", "beaver", "bench", "berry", "birch", "bird", "bison", "blade", "blaze", "blend",
  "block", "bloom", "board", "boat", "bolt", "bonus", "boots", "brave", "bread", "brick",
  "brisk", "broom", "brush", "bunny", "cabin", "cable", "cacao", "camel", "candy", "canoe",
  "canyon", "cargo", "carol", "cedar", "chalk", "charm", "cheek", "chess", "chief", "chili",
  "chime", "chirp", "cider", "cinder", "clamp", "clay", "clever", "cliff", "cloak", "clove",
  "clover", "coach", "coast", "cobra", "cocoa", "comet", "coral", "couch", "cove", "crane",
  "crate", "cream", "creek", "crest", "crisp", "crown", "cube", "curve", "daisy", "dance",
  "dawn", "delta", "dense", "depot", "diary", "diver", "dodge", "donut", "dove", "draft",
  "dream", "drift", "drum", "dune", "eagle", "earth", "east", "ember", "emu", "epoch",
  "ether", "extra", "fable", "fancy", "fawn", "feast", "felt", "fern", "ferry", "field",
  "finch", "flame", "flare", "flask", "fleet", "flint", "float", "flock", "flour", "flute",
  "foam", "forest", "fox", "frame", "frost", "fudge", "gauge", "gecko", "ginger", "glass",
  "glide", "globe", "glow", "gold", "grape", "grass", "gravel", "green", "grid", "grove",
  "guava", "gulf", "hail", "hare", "harp", "hawk", "hazel", "heap", "hedge", "helm",
  "heron", "hill", "hollow", "honey", "horse", "hound", "hush", "ice", "iris", "iron",
  "island", "ivory", "jade", "jazz", "jelly", "jet", "jewel", "jolt", "juice", "jump",
  "kayak", "keel", "kettle", "kite", "kiwi", "koala", "lace", "lake", "lamp", "lance",
  "lantern", "larch", "lark", "latch", "leaf", "ledge", "lemon", "lever", "lily", "lime",
  "linen", "lion", "llama", "loft", "lotus", "lunar", "lynx", "magnet", "mango", "maple",
  "marble", "marsh", "meadow", "medal", "melon", "mesa", "mint", "mist", "moose", "moss",
  "moth", "motor", "mound", "mouse", "mural", "nectar", "nest", "noble", "north", "nova",
  "oak", "oasis", "ocean", "olive", "onyx", "opal", "orbit", "otter", "owl", "oxen",
  "palm", "panda", "panel", "pansy", "parcel", "peach", "pearl", "pebble", "pecan", "penny",
  "petal", "piano", "pilot", "pine", "pixel", "plank", "plaza", "plum", "polar", "pond",
  "poppy", "prism", "puma", "quail", "quartz", "quiet", "quill", "quilt", "radar", "raft",
  "rally", "ranch", "raven", "reef", "relay", "rhino", "ridge", "river", "robin", "robot",
  "rock", "rose", "ruby", "rust", "saber", "salt", "sand", "satin", "sauce", "scarf",
  "scout", "seal", "sedan", "shade", "shale", "shard", "shark", "shell", "shrub", "silk",
  "silver", "siren", "skate", "sketch", "sky", "slate", "sloth", "smog", "snail", "snow",
  "solar", "sonic", "spark", "spice", "spine", "spore", "sprout", "spruce", "squid", "stag",
  "star", "steam", "steel", "stone", "storm", "stove", "straw", "stream", "sugar", "summit",
  "sun", "surf", "swan", "sword", "syrup", "table", "tango", "taper", "tarp", "teak",
  "tempo", "tent", "thorn", "thumb", "tiger", "tile", "timber", "toast", "tofu", "tonic",
  "topaz", "torch", "totem", "tower", "trail", "trout", "tulip", "tundra", "turf", "tusk",
  "ultra", "umber", "unity", "urban", "valley", "vapor", "vault", "velvet", "vine", "viola",
  "violet", "vivid", "vortex", "wagon", "walnut", "wave", "wax", "weave", "whale", "wheat",
  "wheel", "whisk", "willow", "wind", "wolf", "wood", "wren", "yacht", "yarn", "yeast",
  "yield", "yoga", "zebra", "zephyr", "zest", "zinc", "zone",
] as const;
